### ISSUE TITLE
python setup.py install shows Finished but not success actually

### ISSUE THREAD

**Issue by ivy-dong** [arxanchain/wallet-sdk-py#13]
after I run 
`python setup.py install `,
shows me : Finished processing dependencies for wallet-sdk-py==1.5.0.
but when i run
`python -c 'import imp;print imp.find_module("api")[1]'`
shows error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named api
```
pls check this.

**Comment by Honghaohan2013** [comment]
fixed
