### ISSUE TITLE
after pip install run python setup.py install error

### ISSUE THREAD

**Issue by ivy-dong** [arxanchain/wallet-sdk-py#21]
first i run `pip install -r requirements.txt`, waiting for a long time, finished.
then i run "python setup.py install ", shows error:
`error in wallet-sdk-py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'-e git+g'"`

**Comment by Honghaohan2013** [comment]
Fixed.
